name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: stable
          cache: true

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
