# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: pub.dev

    steps:
      - uses: actions/checkout@v6

      - name: Set up Dart OIDC
        uses: dart-lang/setup-dart@v1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: stable
          cache: true

      - name: Install dependencies
        run: dart pub get

      - name: Publish - dry run
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish --force
